version: '3.5'
services:
    db:
      container_name: db_noctua
      image: mongo
      command: mongod --quiet --logpath /dev/null
      ports: 
          - 27017:27017
    
    metabase:
        container_name: metabase
        image: metabase/metabase
        ports: 
            - "1515:3000"

    api:
        depends_on:
            - db
        volumes: 
            - ./server:/app
            - ./server/node_modules:/app/node_modules
        container_name: backend_noctua
        environment:
            - DATABASE_URL=mongodb+srv://Noctua:C5JibXCZ1UBfWLlP@cluster0.cx2qk.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
        build:
            context: ./server
        ports:
            - "5000:5000"
        command: npm start
    
    
    front: 
        environment:
            CHOKIDAR_USEPOLLING: "true"
        volumes: 
            - ./front:/app
            - ./front/node_modules:/app/node_modules
        container_name: frontend_noctua
        build:
            context: ./front
            dockerfile: Dockerfile.dev
        command: yarn start
        ports:
            - "3000:3000"
        depends_on:
            - api

   
